/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    experiences: Experience;
    skills: Skill;
    educations: Education;
    certifications: Certification;
    'kpr-loans': KprLoan;
    'kpr-rate-tiers': KprRateTier;
    'kpr-schedule': KprSchedule;
    'kpr-extra-payments': KprExtraPayment;
    'kpr-reminders': KprReminder;
    'kpr-simulations': KprSimulation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experiences: ExperiencesSelect<false> | ExperiencesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    educations: EducationsSelect<false> | EducationsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    'kpr-loans': KprLoansSelect<false> | KprLoansSelect<true>;
    'kpr-rate-tiers': KprRateTiersSelect<false> | KprRateTiersSelect<true>;
    'kpr-schedule': KprScheduleSelect<false> | KprScheduleSelect<true>;
    'kpr-extra-payments': KprExtraPaymentsSelect<false> | KprExtraPaymentsSelect<true>;
    'kpr-reminders': KprRemindersSelect<false> | KprRemindersSelect<true>;
    'kpr-simulations': KprSimulationsSelect<false> | KprSimulationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    profile: Profile;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: string;
  title: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  thumbnail?: (string | null) | Media;
  techStack?:
    | {
        technology: string;
        id?: string | null;
      }[]
    | null;
  repoUrl?: string | null;
  liveUrl?: string | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences".
 */
export interface Experience {
  id: string;
  company: string;
  logo?: (string | null) | Media;
  role: string;
  startDate: string;
  endDate?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contributions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: string;
  name: string;
  category: 'Frontend' | 'Backend' | 'DevOps' | 'Other';
  icon?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations".
 */
export interface Education {
  id: string;
  school: string;
  logo?: (string | null) | Media;
  degree: string;
  period: string;
  gpa?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: string;
  name: string;
  year: string;
  issuer: string;
  credentialUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Metadata pinjaman KPR
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-loans".
 */
export interface KprLoan {
  id: string;
  borrowerName: string;
  coBorrower?: string | null;
  bankName: string;
  branch?: string | null;
  loanAmount: number;
  housePrice: number;
  downPayment: number;
  tenorMonths: number;
  firstPayment: string;
  offeringLetterRef?: string | null;
  propertyAddress?: string | null;
  certificateNo?: string | null;
  collateralValue?: number | null;
  /**
   * Contoh: 10 = 10%
   */
  penaltyBeforeMinTenor?: number | null;
  /**
   * Contoh: 2.5 = 2.5%
   */
  penaltyAfterMinTenor?: number | null;
  /**
   * Setelah periode ini, penalti turun
   */
  minTenorMonths?: number | null;
  minPartialPrepayment?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Tier suku bunga berjenjang (stepped fixed rate)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-rate-tiers".
 */
export interface KprRateTier {
  id: string;
  loan: string | KprLoan;
  /**
   * 1, 2, 3, dst.
   */
  tierOrder: number;
  startMonth: number;
  endMonth: number;
  /**
   * Contoh: 4.75, 8.00, 10.25
   */
  ratePct: number;
  installment: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Jadwal angsuran 240 bulan (seeded from CSV)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-schedule".
 */
export interface KprSchedule {
  id: string;
  loan: string | KprLoan;
  monthNumber: number;
  calendarDate: string;
  principalPortion: number;
  interestPortion: number;
  totalInstallment: number;
  outstandingBalance: number;
  interestRate: number;
  isPaid?: boolean | null;
  paidDate?: string | null;
  paidAmount?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Log pembayaran ekstra / pelunasan sebagian
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-extra-payments".
 */
export interface KprExtraPayment {
  id: string;
  loan: string | KprLoan;
  paymentDate: string;
  amount: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Konfigurasi email reminder angsuran
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-reminders".
 */
export interface KprReminder {
  id: string;
  loan: string | KprLoan;
  email: string;
  /**
   * Reminder dikirim pada tanggal ini setiap bulan (1-28)
   */
  reminderDay: number;
  isActive?: boolean | null;
  lastSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Skenario simulasi pembayaran yang tersimpan
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-simulations".
 */
export interface KprSimulation {
  id: string;
  loan: string | KprLoan;
  name: string;
  scenarioType: 'early_payoff' | 'extra_payment' | 'refinance';
  /**
   * Input parameter simulasi (JSON)
   */
  params:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Hasil perhitungan simulasi (JSON)
   */
  results:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: string | Project;
      } | null)
    | ({
        relationTo: 'experiences';
        value: string | Experience;
      } | null)
    | ({
        relationTo: 'skills';
        value: string | Skill;
      } | null)
    | ({
        relationTo: 'educations';
        value: string | Education;
      } | null)
    | ({
        relationTo: 'certifications';
        value: string | Certification;
      } | null)
    | ({
        relationTo: 'kpr-loans';
        value: string | KprLoan;
      } | null)
    | ({
        relationTo: 'kpr-rate-tiers';
        value: string | KprRateTier;
      } | null)
    | ({
        relationTo: 'kpr-schedule';
        value: string | KprSchedule;
      } | null)
    | ({
        relationTo: 'kpr-extra-payments';
        value: string | KprExtraPayment;
      } | null)
    | ({
        relationTo: 'kpr-reminders';
        value: string | KprReminder;
      } | null)
    | ({
        relationTo: 'kpr-simulations';
        value: string | KprSimulation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  thumbnail?: T;
  techStack?:
    | T
    | {
        technology?: T;
        id?: T;
      };
  repoUrl?: T;
  liveUrl?: T;
  featured?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experiences_select".
 */
export interface ExperiencesSelect<T extends boolean = true> {
  company?: T;
  logo?: T;
  role?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  contributions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "educations_select".
 */
export interface EducationsSelect<T extends boolean = true> {
  school?: T;
  logo?: T;
  degree?: T;
  period?: T;
  gpa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  year?: T;
  issuer?: T;
  credentialUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-loans_select".
 */
export interface KprLoansSelect<T extends boolean = true> {
  borrowerName?: T;
  coBorrower?: T;
  bankName?: T;
  branch?: T;
  loanAmount?: T;
  housePrice?: T;
  downPayment?: T;
  tenorMonths?: T;
  firstPayment?: T;
  offeringLetterRef?: T;
  propertyAddress?: T;
  certificateNo?: T;
  collateralValue?: T;
  penaltyBeforeMinTenor?: T;
  penaltyAfterMinTenor?: T;
  minTenorMonths?: T;
  minPartialPrepayment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-rate-tiers_select".
 */
export interface KprRateTiersSelect<T extends boolean = true> {
  loan?: T;
  tierOrder?: T;
  startMonth?: T;
  endMonth?: T;
  ratePct?: T;
  installment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-schedule_select".
 */
export interface KprScheduleSelect<T extends boolean = true> {
  loan?: T;
  monthNumber?: T;
  calendarDate?: T;
  principalPortion?: T;
  interestPortion?: T;
  totalInstallment?: T;
  outstandingBalance?: T;
  interestRate?: T;
  isPaid?: T;
  paidDate?: T;
  paidAmount?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-extra-payments_select".
 */
export interface KprExtraPaymentsSelect<T extends boolean = true> {
  loan?: T;
  paymentDate?: T;
  amount?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-reminders_select".
 */
export interface KprRemindersSelect<T extends boolean = true> {
  loan?: T;
  email?: T;
  reminderDay?: T;
  isActive?: T;
  lastSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kpr-simulations_select".
 */
export interface KprSimulationsSelect<T extends boolean = true> {
  loan?: T;
  name?: T;
  scenarioType?: T;
  params?: T;
  results?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: string;
  name: string;
  headline: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  avatar?: (string | null) | Media;
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  name?: T;
  headline?: T;
  bio?: T;
  avatar?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}