import type { CollectionConfig } from 'payload'
import { aiInsightAccess } from '@/access/monetalis'

export const KprAiInsights: CollectionConfig = {
  slug: 'kpr-ai-insights',
  access: aiInsightAccess,
  admin: {
    group: 'Monetalis',
    useAsTitle: 'summary',
    description: 'AI-generated KPR insights yang tersimpan per loan',
    defaultColumns: ['loan', 'generatedAt', 'status', 'promptVersion'],
  },
  fields: [
    {
      name: 'loan',
      type: 'relationship',
      relationTo: 'kpr-loans',
      required: true,
      label: 'Pinjaman',
    },
    {
      name: 'generatedBy',
      type: 'text',
      required: true,
      label: 'Generated By (Logto Subject)',
      admin: { readOnly: true },
    },
    {
      name: 'generatedAt',
      type: 'date',
      required: true,
      label: 'Generated At',
      admin: { readOnly: true },
    },
    {
      name: 'promptVersion',
      type: 'text',
      required: true,
      label: 'Prompt Version',
      admin: { readOnly: true },
    },
    {
      name: 'model',
      type: 'text',
      label: 'AI Model',
      admin: { readOnly: true },
    },
    {
      name: 'sourceSnapshot',
      type: 'json',
      required: true,
      label: 'Source Snapshot',
      admin: { readOnly: true },
    },
    {
      name: 'summary',
      type: 'textarea',
      required: true,
      label: 'Summary',
      maxLength: 2000,
    },
    {
      name: 'financialPosition',
      type: 'textarea',
      required: true,
      label: 'Financial Position',
      maxLength: 3000,
    },
    {
      name: 'risks',
      type: 'json',
      required: true,
      label: 'Risks',
    },
    {
      name: 'opportunities',
      type: 'json',
      required: true,
      label: 'Opportunities',
    },
    {
      name: 'actions',
      type: 'json',
      required: true,
      label: 'Action Plan',
    },
    {
      name: 'assumptions',
      type: 'json',
      required: true,
      label: 'Assumptions',
    },
    {
      name: 'disclaimer',
      type: 'textarea',
      required: true,
      label: 'Disclaimer',
      maxLength: 1000,
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'completed',
      options: [
        { label: 'Completed', value: 'completed' },
        { label: 'Failed', value: 'failed' },
      ],
      admin: { readOnly: true },
    },
    {
      name: 'errorMessage',
      type: 'textarea',
      label: 'Error Message',
      maxLength: 2000,
      admin: { readOnly: true },
    },
  ],
  indexes: [
    {
      fields: ['loan', 'generatedAt'],
    },
  ],
}
